import React, { useState } from 'react';
import { usePipeline } from '../../context/PipelineContext';
import { Award, Trophy, Download, Medal, BarChart2, ChevronDown, ChevronUp, Zap, Star } from 'lucide-react';

const RANK_COLORS = ['text-neon-green', 'text-neon-blue', 'text-accent-amber'];
const RANK_BG = ['bg-neon-green/10 border-neon-green/40', 'bg-neon-blue/10 border-neon-blue/40', 'bg-accent-amber/10 border-accent-amber/40'];
const RANK_ICONS = [Trophy, Medal, Award];
const RANK_LABELS = ['🥇 #1 Top Lead', '🥈 #2 Runner-up', '🥉 #3 Third'];

export const Module5QSAR: React.FC = () => {
  const { state, runModule5 } = usePipeline();
  const mod5Data = state.module5Data;
  const mod1Data = state.module1Data;
  const mod2Data = state.module2Data;
  const mod4Data = state.module4Data;

  const [showFullTable, setShowFullTable] = useState(false);
  const [showChart, setShowChart] = useState(true);
  const [isRunning, setIsRunning] = useState(false);
  const [progress, setProgress] = useState(0);

  const handleRunQsar = () => {
    setIsRunning(true);
    setProgress(0);
    // Animate progress bar
    const interval = setInterval(() => {
      setProgress(p => {
        if (p >= 100) { clearInterval(interval); setIsRunning(false); return 100; }
        return p + Math.random() * 12;
      });
    }, 80);
    runModule5();
    setTimeout(() => { clearInterval(interval); setIsRunning(false); setProgress(100); }, 1200);
  };

  const exportJson = () => {
    const data = {
      pipelineName: 'BioHelix MLOps: End-to-End Computational Drug Discovery',
      date: new Date().toISOString(),
      targetID: 'TRG-8942-PX',
      targetGene: mod1Data?.geneName,
      gcContent: mod1Data?.gcContent,
      sequenceLength: mod1Data?.sequenceLength,
      proteinSequence: mod1Data?.proteinSequence,
      esmFoldPlddt: mod2Data?.meanPlddt,
      esmFoldSource: mod2Data?.source,
      topLeadDrugCandidates: mod5Data?.topCandidates,
      allPredictions: mod5Data?.predictions,
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `BioHelix_QSAR_Report_${mod1Data?.geneName ?? 'TRG'}_${new Date().toISOString().split('T')[0]}.json`;
    a.click();
  };

  const exportReport = () => {
    const top3 = mod5Data?.topCandidates ?? [];
    const lines = [
      '╔══════════════════════════════════════════════════════════════════╗',
      '║        BIOHELIX MLOPS — QSAR DRUG DISCOVERY REPORT              ║',
      '╚══════════════════════════════════════════════════════════════════╝',
      '',
      `Date: ${new Date().toLocaleString()}`,
      `Target Gene: ${mod1Data?.geneName ?? 'N/A'}`,
      `Target ID: TRG-8942-PX`,
      `DNA Length: ${mod1Data?.sequenceLength ?? 'N/A'} bp`,
      `GC Content: ${mod1Data?.gcContent ?? 'N/A'}%`,
      `Protein Length: ${mod1Data?.proteinSequence?.length ?? 'N/A'} AA`,
      `ESMFold pLDDT: ${mod2Data?.meanPlddt ?? 'N/A'}`,
      `ESMFold Source: ${mod2Data?.source ?? 'N/A'}`,
      `Total Compounds Screened: ${mod4Data?.rawMolecules.length ?? 'N/A'}`,
      `Compounds Passing Lipinski: ${mod4Data?.filteredMolecules.length ?? 'N/A'}`,
      '',
      '══ TOP 3 LEAD DRUG CANDIDATES ══',
      '',
      ...top3.flatMap((c, i) => [
        `${['#1 TOP LEAD', '#2 RUNNER-UP', '#3 THIRD'][i]}`,
        `  Name: ${c.molecule.name}`,
        `  ID: ${c.molecule.id}`,
        `  SMILES: ${c.molecule.smiles}`,
        `  Predicted pIC50: ${c.pIC50}`,
        `  Binding Affinity Ki: ${c.bindingAffinityKi} nM`,
        `  Docking Score: ${c.dockingScore} kcal/mol`,
        `  Drug-Likeness Score: ${(c.drugLikenessScore * 100).toFixed(0)}%`,
        `  MW: ${c.molecule.mw} Da | LogP: ${c.molecule.logP} | HBD: ${c.molecule.hbd} | HBA: ${c.molecule.hba} | TPSA: ${c.molecule.tpsa} Å²`,
        '',
      ]),
      '══════════════════════════════════════════════════════════════════',
      'Generated by BioHelix MLOps Platform v1.4.2',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `BioHelix_Report_${mod1Data?.geneName ?? 'TRG'}.txt`;
    a.click();
  };

  const predictions = mod5Data?.predictions ?? [];
  const maxPIC50 = predictions.length > 0 ? Math.max(...predictions.map(p => p.pIC50)) : 10;
  const minPIC50 = predictions.length > 0 ? Math.min(...predictions.map(p => p.pIC50)) : 0;
  const range = maxPIC50 - minPIC50 || 1;

  const candidateCount = mod4Data?.filteredMolecules.length ?? 0;

  return (
    <div className="space-y-4 max-w-6xl">
      {/* Stage Banner */}
      <div className="bg-surface-container border border-border-subtle rounded-xl p-4 glass-panel">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <div className="flex items-center space-x-2 text-xs font-mono text-neon-green uppercase tracking-wider mb-1">
              <Award className="w-4 h-4" />
              <span>🏆 Stage 5: QSAR Predictive Inference & Drug Ranking</span>
            </div>
            <h2 className="text-lg font-display font-bold text-text-bright">Random Forest QSAR ML Engine — Batch Inference</h2>
            <p className="text-xs text-text-muted mt-0.5 max-w-3xl">
              Pre-trained Random Forest model scores all filtered candidates using <strong className="text-neon-blue">Morgan Fingerprint feature vectors</strong>. Ensemble trees simulate structure-activity relationship (SAR). Ranked by predicted pIC50 and binding affinity (ΔG).
            </p>
          </div>
        </div>
      </div>

      {/* Model Registry Banner */}
      <div className="bg-surface-container border border-border-subtle rounded-xl p-3 font-mono text-xs flex flex-wrap gap-4 items-center">
        <div className="flex items-center gap-1.5">
          <Star className="w-3 h-3 text-neon-green" />
          <span className="text-text-muted">Model:</span>
          <span className="text-neon-green font-bold">Random_Forest_QSAR_v1.4.pkl</span>
        </div>
        <div><span className="text-text-muted">Feature Vector:</span> <span className="text-neon-blue">Morgan Fingerprints (radius=2, 2048-bit)</span></div>
        <div><span className="text-text-muted">Candidates:</span> <span className="text-text-bright font-bold">{candidateCount} molecules</span></div>
        <div><span className="text-text-muted">Target:</span> <span className="text-neon-green font-bold">{mod1Data?.geneName ?? 'TRG-8942-PX'}</span></div>
        <div><span className="text-text-muted">Protein Length:</span> <span className="text-text-bright">{mod1Data?.proteinSequence?.length ?? '—'} AA</span></div>
      </div>

      {/* Execute Button */}
      <button
        onClick={handleRunQsar}
        disabled={!mod4Data || candidateCount === 0 || isRunning}
        className="w-full bg-neon-green/20 hover:bg-neon-green/30 border border-neon-green/60 text-neon-green font-mono font-bold text-sm py-3 rounded-xl flex items-center justify-center gap-2 transition-all disabled:opacity-40 shadow-sm shadow-neon-green/10 active:scale-[0.98]"
      >
        <Zap className="w-5 h-5" />
        🚀 EXECUTE BATCH INFERENCE ON {candidateCount} MOLECULES
      </button>

      {/* Progress bar during inference */}
      {isRunning && (
        <div className="bg-surface-container border border-neon-green/30 rounded-xl p-4 font-mono text-xs text-neon-green">
          <div className="flex justify-between mb-1">
            <span>Running Random Forest Ensemble...</span>
            <span>{Math.min(100, Math.round(progress))}%</span>
          </div>
          <div className="h-2 bg-surface-base rounded-full overflow-hidden">
            <div
              className="h-full bg-gradient-to-r from-neon-green to-neon-blue rounded-full transition-all duration-200"
              style={{ width: `${Math.min(100, progress)}%` }}
            />
          </div>
          <div className="mt-1 text-[10px] text-text-muted animate-pulse">
            Evaluating Morgan fingerprints → Computing tree ensemble → Ranking by pIC50...
          </div>
        </div>
      )}

      {mod5Data && (
        <div className="space-y-4">
          {/* TOP 3 Cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {mod5Data.topCandidates.map((c, idx) => {
              const Icon = RANK_ICONS[idx];
              return (
                <div key={c.molecule.id} className={`rounded-xl border p-4 glass-panel ${RANK_BG[idx]}`}>
                  <div className="flex items-center justify-between mb-2">
                    <div className={`text-xs font-mono font-bold ${RANK_COLORS[idx]}`}>{RANK_LABELS[idx]}</div>
                    <Icon className={`w-5 h-5 ${RANK_COLORS[idx]}`} />
                  </div>
                  <div className="font-display font-bold text-sm text-text-bright mb-0.5 truncate" title={c.molecule.name}>{c.molecule.name}</div>
                  <div className="text-[10px] font-mono text-text-muted mb-3">{c.molecule.id}</div>

                  <div className="space-y-1.5 font-mono text-xs">
                    <div className="flex justify-between">
                      <span className="text-text-muted">pIC50:</span>
                      <span className={`font-bold ${RANK_COLORS[idx]}`}>{c.pIC50} <span className="text-text-muted text-[10px]">({c.pIC50 >= 8 ? 'High' : c.pIC50 >= 7 ? 'Med-High' : 'Medium'})</span></span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-text-muted">Ki (nM):</span>
                      <span className="font-bold text-text-bright">{c.bindingAffinityKi}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-text-muted">ΔG:</span>
                      <span className="font-bold text-text-bright">{c.dockingScore} kcal/mol</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-text-muted">Drug-likeness:</span>
                      <span className={`font-bold ${RANK_COLORS[idx]}`}>{(c.drugLikenessScore * 100).toFixed(0)}%</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-text-muted">MW / LogP:</span>
                      <span className="text-text-bright">{c.molecule.mw} Da / {c.molecule.logP}</span>
                    </div>
                  </div>

                  {/* Drug-likeness bar */}
                  <div className="mt-3">
                    <div className="h-1.5 bg-surface-base rounded-full overflow-hidden">
                      <div className={`h-full ${idx === 0 ? 'bg-neon-green' : idx === 1 ? 'bg-neon-blue' : 'bg-accent-amber'} rounded-full`} style={{ width: `${c.drugLikenessScore * 100}%` }} />
                    </div>
                    <div className="text-[9px] font-mono text-text-muted mt-0.5">Drug-Likeness Score</div>
                  </div>

                  {/* SMILES */}
                  <div className="mt-2 bg-surface-base/80 rounded p-1.5 text-[9px] font-mono text-text-muted break-all leading-relaxed max-h-10 overflow-hidden">
                    {c.molecule.smiles}
                  </div>
                </div>
              );
            })}
          </div>

          {/* pIC50 Distribution SVG Chart */}
          <div className="bg-surface-container border border-border-subtle rounded-xl glass-panel overflow-hidden">
            <button
              onClick={() => setShowChart(p => !p)}
              className="w-full flex items-center justify-between p-4 text-sm font-display font-semibold text-text-bright"
            >
              <div className="flex items-center gap-2">
                <BarChart2 className="w-4 h-4 text-neon-blue" />
                pIC50 Score Distribution ({predictions.length} Candidates)
              </div>
              {showChart ? <ChevronUp className="w-4 h-4 text-text-muted" /> : <ChevronDown className="w-4 h-4 text-text-muted" />}
            </button>
            {showChart && (
              <div className="px-4 pb-4">
                {/* SVG bar chart */}
                <svg width="100%" height="120" viewBox={`0 0 ${Math.max(600, predictions.slice(0, 60).length * 10)} 120`} preserveAspectRatio="xMidYMid meet" className="w-full">
                  {predictions.slice(0, 60).map((pred, idx) => {
                    const barH = Math.max(4, ((pred.pIC50 - minPIC50) / range) * 90);
                    const x = idx * 10 + 2;
                    const y = 100 - barH;
                    const isTop3 = pred.rank <= 3;
                    const color = isTop3 ? '#00FF7F' : idx % 2 === 0 ? '#00E0FF40' : '#00E0FF30';
                    return (
                      <g key={pred.molecule.id}>
                        <rect x={x} y={y} width={7} height={barH} fill={color} rx={1.5}>
                          <title>{pred.molecule.name} — pIC50: {pred.pIC50}</title>
                        </rect>
                        {isTop3 && (
                          <text x={x + 3.5} y={y - 3} textAnchor="middle" fontSize="7" fill="#00FF7F">#{pred.rank}</text>
                        )}
                      </g>
                    );
                  })}
                  {/* Baseline */}
                  <line x1="0" y1="100" x2="100%" y2="100" stroke="#333" strokeWidth="0.5" />
                </svg>
                <div className="flex justify-between text-[9px] font-mono text-text-muted mt-1">
                  <span className="text-neon-green">■ Top 3 Lead Candidates</span>
                  <span>pIC50 range: {minPIC50.toFixed(1)} – {maxPIC50.toFixed(1)}</span>
                  <span>Rank #{predictions.length} (Weakest)</span>
                </div>
              </div>
            )}
          </div>

          {/* Full Predictions Table */}
          <div className="bg-surface-container border border-border-subtle rounded-xl glass-panel overflow-hidden">
            <button
              onClick={() => setShowFullTable(p => !p)}
              className="w-full flex items-center justify-between p-4 text-sm font-display font-semibold text-text-bright"
            >
              <span>Full QSAR Predictions Table ({predictions.length} candidates)</span>
              {showFullTable ? <ChevronUp className="w-4 h-4 text-text-muted" /> : <ChevronDown className="w-4 h-4 text-text-muted" />}
            </button>
            {showFullTable && (
              <div className="overflow-x-auto border-t border-border-subtle max-h-80">
                <table className="w-full text-xs font-mono text-left">
                  <thead className="bg-surface-base text-text-muted text-[10px] sticky top-0 border-b border-border-subtle z-10">
                    <tr>
                      <th className="p-2">Rank</th>
                      <th className="p-2">Name</th>
                      <th className="p-2">SMILES</th>
                      <th className="p-2">pIC50</th>
                      <th className="p-2">Ki (nM)</th>
                      <th className="p-2">ΔG (kcal/mol)</th>
                      <th className="p-2">Drug-Like</th>
                      <th className="p-2">MW</th>
                      <th className="p-2">LogP</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border-subtle">
                    {predictions.map(p => (
                      <tr key={p.molecule.id} className={`hover:bg-surface-container-high transition-colors ${p.rank <= 3 ? 'bg-neon-green/5' : ''}`}>
                        <td className={`p-2 font-bold ${p.rank <= 3 ? 'text-neon-green' : 'text-text-muted'}`}>#{p.rank}</td>
                        <td className="p-2 text-text-bright max-w-[150px] truncate" title={p.molecule.name}>{p.molecule.name}</td>
                        <td className="p-2 text-text-muted max-w-[120px] truncate text-[9px]" title={p.molecule.smiles}>{p.molecule.smiles}</td>
                        <td className={`p-2 font-bold ${p.pIC50 >= 8 ? 'text-neon-green' : p.pIC50 >= 7 ? 'text-neon-blue' : 'text-text-muted'}`}>{p.pIC50}</td>
                        <td className="p-2 text-neon-green">{p.bindingAffinityKi}</td>
                        <td className="p-2 text-text-muted">{p.dockingScore}</td>
                        <td className="p-2 text-text-muted">{(p.drugLikenessScore * 100).toFixed(0)}%</td>
                        <td className="p-2 text-text-muted">{p.molecule.mw}</td>
                        <td className="p-2 text-text-muted">{p.molecule.logP}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          {/* Export Actions */}
          <div className="flex flex-wrap gap-3">
            <button
              onClick={exportJson}
              className="flex items-center gap-2 bg-neon-green/20 hover:bg-neon-green/30 border border-neon-green/50 text-neon-green font-mono font-bold text-xs py-2.5 px-5 rounded-xl transition-all active:scale-[0.98]"
            >
              <Download className="w-4 h-4" />
              📥 Export Full Report (JSON)
            </button>
            <button
              onClick={exportReport}
              className="flex items-center gap-2 bg-surface-container-high hover:bg-surface-container border border-border-subtle text-text-muted font-mono font-bold text-xs py-2.5 px-5 rounded-xl transition-all active:scale-[0.98]"
            >
              <Download className="w-4 h-4" />
              📄 Download Audit Report (TXT)
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
