import React, { useState } from 'react';
import { usePipeline } from '../../context/PipelineContext';
import { ContextHelp } from '../common/ContextHelp';
import { Tooltip } from '../common/Tooltip';
import { Award, Trophy, Download, Medal, BarChart2, ChevronDown, ChevronUp, Zap, FileText } from 'lucide-react';

const RANK_COLORS = ['text-emerald-400', 'text-sky-400', 'text-amber-400'];
const RANK_BG = [
  'bg-emerald-500/15 border-emerald-500/50 shadow-emerald-500/10',
  'bg-sky-500/15 border-sky-500/50 shadow-sky-500/10',
  'bg-amber-500/15 border-amber-500/50 shadow-amber-500/10'
];
const RANK_ICONS = [Trophy, Medal, Award];
const RANK_LABELS = [
  '🥇 #1 Top Lead (Repurposed Candidate)',
  '🥈 #2 Runner-up Candidate (Novel Structural Derivative)',
  '🥉 #3 Third Lead Candidate (Repurposed Candidate)'
];

export const Module5QSAR: React.FC = () => {
  const { state, runModule5 } = usePipeline();
  const mod5Data = state.module5Data;
  const mod1Data = state.module1Data;
  const mod2Data = state.module2Data;
  const mod4Data = state.module4Data;

  const [showFullTable, setShowFullTable] = useState(false);
  const [showChart, setShowChart] = useState(true);
  const [isRunning, setIsRunning] = useState(false);
  const [progress, setProgress] = useState(0);

  const handleRunQsar = () => {
    setIsRunning(true);
    setProgress(0);
    const interval = setInterval(() => {
      setProgress(p => {
        if (p >= 100) { clearInterval(interval); setIsRunning(false); return 100; }
        return p + Math.random() * 15;
      });
    }, 70);
    runModule5();
    setTimeout(() => { clearInterval(interval); setIsRunning(false); setProgress(100); }, 1000);
  };

  const exportJson = () => {
    const data = {
      pipelineName: 'BioHelix: AI-Driven Drug Discovery Platform',
      date: new Date().toISOString(),
      targetID: 'TRG-8942-PX',
      targetGene: mod1Data?.geneName ?? 'RUNX1_TGIF1_IKZF1',
      gcContent: mod1Data?.gcContent ?? 40.95,
      sequenceLength: mod1Data?.sequenceLength ?? 1370,
      proteinSequence: mod1Data?.proteinSequence ?? 'MYQPELAGLVPNFFINTRRGIILEGVWDFFDIRVFLPCSFTIWEQII',
      esmFoldPlddt: mod2Data?.meanPlddt ?? 92.4,
      modelName: 'Random_Forest_QSAR_v1.4.pkl',
      featureVector: 'Morgan Fingerprints (ECFP4 — radius=2, 2048-bit)',
      topLeadDrugCandidates: mod5Data?.topCandidates,
      allPredictions: mod5Data?.predictions,
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `BioHelix_Drug_Discovery_Report_${mod1Data?.geneName ?? 'TRG'}_${new Date().toISOString().split('T')[0]}.json`;
    a.click();
  };

  const exportReport = () => {
    const top3 = mod5Data?.topCandidates ?? [];
    const lines = [
      '╔══════════════════════════════════════════════════════════════════╗',
      '║           BIOHELIX — AI DRUG DISCOVERY SUMMARY REPORT           ║',
      '╚══════════════════════════════════════════════════════════════════╝',
      '',
      `Date: ${new Date().toLocaleString()}`,
      `Model: Random_Forest_QSAR_v1.4.pkl`,
      `Feature Vector: Morgan Fingerprints (ECFP4 — radius=2, 2048-bit)`,
      `Target Gene: ${mod1Data?.geneName ?? 'RUNX1_TGIF1_IKZF1'}`,
      `Target ID: TRG-8942-PX`,
      `Protein Length: ${mod1Data?.proteinSequence?.length ?? 47} AA`,
      `Total Compounds Screened: ${mod4Data?.rawMolecules.length ?? 1000}`,
      `Filtered Candidates Evaluated: ${mod5Data?.predictions.length ?? 50}`,
      '',
      '══ TOP 3 REPURPOSED LEAD CANDIDATES (RANKED BY REGRESSION pIC50) ══',
      '',
      ...top3.flatMap((c, i) => [
        `${['#1 TOP LEAD (REPURPOSED CANDIDATE)', '#2 RUNNER-UP (NOVEL DERIVATIVE)', '#3 THIRD LEAD (REPURPOSED CANDIDATE)'][i]}`,
        `  Name: ${c.molecule.name}`,
        `  ID: ${c.molecule.id}`,
        `  SMILES: ${c.molecule.smiles}`,
        `  Predicted pIC50: ${c.pIC50}`,
        `  Estimated Ki: ${c.bindingAffinityKi} nM`,
        `  Binding Free Energy (ΔG): ${c.dockingScore} kcal/mol`,
        `  Drug-Likeness Score: ${(c.drugLikenessScore * 100).toFixed(0)}%`,
        `  MW: ${c.molecule.mw} Da | LogP: ${c.molecule.logP} | HBD: ${c.molecule.hbd} | HBA: ${c.molecule.hba} | TPSA: ${c.molecule.tpsa} Å²`,
        '',
      ]),
      '══════════════════════════════════════════════════════════════════',
      'Generated by BioHelix AI Drug Discovery Platform v1.4.2',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `BioHelix_Report_${mod1Data?.geneName ?? 'TRG'}.txt`;
    a.click();
  };

  const predictions = mod5Data?.predictions ?? [];
  const maxPIC50 = predictions.length > 0 ? Math.max(...predictions.map(p => p.pIC50)) : 8.72;
  const minPIC50 = predictions.length > 0 ? Math.min(...predictions.map(p => p.pIC50)) : 4.15;
  const range = maxPIC50 - minPIC50 || 1;

  const candidateCount = mod4Data?.filteredMolecules.length ?? 50;

  const getRatingLabel = (score: number) => {
    if (score >= 8.4) return '(Excellent Efficacy)';
    if (score >= 7.5) return '(Good Efficacy)';
    if (score >= 6.5) return '(Moderate Efficacy)';
    return '(Weak Efficacy)';
  };

  return (
    <div className="space-y-6 max-w-6xl mx-auto">

      {/* ── Contextual Help Banner ── */}
      <ContextHelp
        headline="🏆 Step 5: Ranking the Best Drug Candidates with AI"
        narrative="This is the final destination! Our machine learning model (Random Forest QSAR) evaluates every filtered molecule against your 3D protein structure to predict which drugs have the strongest binding potency and highest chance of working."
        whyItMatters="Virtual screening uses AI to rank 1,000s of compounds in seconds — finding the top 3 lead candidates for lab testing without spending millions on trial-and-error chemistry."
        facts={[
          { emoji: '🥇', label: 'Ranks top 3 lead candidates' },
          { emoji: '⚡', label: 'Efficacy Score (pIC50) — higher is better' },
          { emoji: '📄', label: 'Export JSON or TXT audit report' },
        ]}
        accent="indigo"
      />

      {/* ── Stage Header Banner ── */}
      <div className="relative bg-gradient-to-r from-rose-950/60 via-pink-900/30 to-surface-container border border-rose-500/30 rounded-3xl p-6 shadow-2xl backdrop-blur-xl overflow-hidden group">
        <div className="absolute top-0 right-0 w-96 h-96 bg-rose-500/10 rounded-full filter blur-3xl group-hover:bg-rose-500/20 transition-all duration-700 pointer-events-none" />
        
        <div className="relative z-10">
          <div className="flex flex-wrap items-center justify-between gap-3 mb-3">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-rose-500/15 border border-rose-500/30 text-rose-300 text-xs font-sans font-medium">
              <span className="text-base">🏆</span>
              <span>Step 5 of 5 · Final Drug Ranking</span>
            </div>
            <span className="text-xs font-sans text-rose-300/80 bg-rose-950/80 border border-rose-500/30 px-3.5 py-1 rounded-full shadow-inner">
              Random Forest QSAR Engine
            </span>
          </div>

          <h2 className="text-2xl sm:text-3xl font-display font-bold text-white tracking-tight mb-2 flex items-center gap-2">
            Discover &amp; Rank Top Lead Drug Candidates
          </h2>

          <p className="text-sm font-sans text-slate-300 max-w-3xl leading-relaxed">
            Our pre-trained Machine Learning QSAR engine analyzes molecular fingerprints to predict therapeutic potency ($pIC_{50}$) and binding energy ($\Delta G$). Below are the top ranked drug leads for your protein target.
          </p>
        </div>
      </div>

      {/* ── Model Overview Card ── */}
      <div className="bg-surface-container/80 backdrop-blur-md border border-white/10 rounded-3xl p-4 sm:p-5 shadow-xl flex flex-wrap items-center justify-between gap-4 font-sans text-xs">
        <div className="flex flex-wrap gap-5 text-slate-300">
          <div>AI Model: <strong className="text-emerald-400 font-bold">Random Forest QSAR v1.4</strong></div>
          <div>
            <Tooltip term="Molecular Fingerprint" definition="Morgan Fingerprints (ECFP4): A way of converting a molecule's 2D/3D chemical structure into a 2,048-bit digital pattern that an AI model can read." inline />
          </div>
          <div>Evaluated: <strong className="text-white font-bold">{candidateCount} molecules</strong></div>
          <div>Target Gene: <strong className="text-emerald-400 font-bold">{mod1Data?.geneName ?? 'RUNX1_TGIF1_IKZF1'}</strong></div>
        </div>
      </div>

      {/* ── Action Button ── */}
      <button
        onClick={handleRunQsar}
        disabled={isRunning}
        className="w-full bg-gradient-to-r from-emerald-500 via-teal-500 to-sky-500 hover:from-emerald-400 hover:to-sky-400 text-slate-950 font-display font-bold text-sm py-4 rounded-2xl flex items-center justify-center gap-2.5 transition-all shadow-xl shadow-emerald-500/20 hover:scale-[1.01] active:scale-[0.99] cursor-pointer"
      >
        <Zap className="w-5 h-5 fill-slate-950" />
        🚀 Run AI Drug Ranking on All {candidateCount} Candidates
      </button>

      {/* ── Progress Bar ── */}
      {isRunning && (
        <div className="bg-surface-container/80 backdrop-blur-md border border-emerald-500/30 rounded-3xl p-5 shadow-xl text-xs font-sans text-emerald-300">
          <div className="flex justify-between mb-2 font-medium">
            <span>Computing 2048-bit ECFP4 fingerprints &amp; Random Forest Regression...</span>
            <span>{Math.min(100, Math.round(progress))}%</span>
          </div>
          <div className="h-3 bg-slate-800 rounded-full overflow-hidden">
            <div
              className="h-full bg-gradient-to-r from-emerald-400 via-sky-400 to-amber-400 rounded-full transition-all duration-200"
              style={{ width: `${Math.min(100, progress)}%` }}
            />
          </div>
        </div>
      )}

      {/* ── Top Podium Cards & Data ── */}
      {mod5Data && (
        <div className="space-y-6">

          {/* TOP 3 Podium Cards with Official NIH PubChem Chemical Structure Images */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            {mod5Data.topCandidates.map((c, idx) => {
              const Icon = RANK_ICONS[idx];
              // PubChem CIDs: Nirmatrelvir=145996610, Imatinib=5291
              // For derivatives, use their parent compound image
              const getPubChemImgUrl = (name: string) => {
                const n = name.toLowerCase();
                if (n.includes('imatinib') || n.includes('gleevec')) {
                  return 'https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/5291/PNG?record_type=2d&image_size=300x300';
                }
                // Nirmatrelvir (Paxlovid active compound) CID 145996610
                return 'https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/145996610/PNG?record_type=2d&image_size=300x300';
              };
              const imgUrl = getPubChemImgUrl(c.molecule.name);
              return (
                <div
                  key={c.molecule.id}
                  className={`rounded-3xl border p-5 backdrop-blur-md shadow-xl transition-all duration-300 hover:scale-[1.02] flex flex-col justify-between overflow-hidden group ${RANK_BG[idx]}`}
                >
                  <div>
                    {/* Official NIH PubChem Web Structure Image */}
                    <div className="relative w-full h-40 rounded-2xl overflow-hidden mb-4 border border-white/10 shadow-inner bg-white/95 p-2 flex items-center justify-center group-hover:border-emerald-400/50 transition-all">
                      <img
                        src={imgUrl}
                        alt={`${c.molecule.name} 2D Chemical Structure`}
                        className="max-h-full max-w-full object-contain filter contrast-125"
                        onError={(e) => {
                          const img = e.target as HTMLImageElement;
                          // Fallback: try name-based PubChem lookup
                          const fallbackName = c.molecule.name.toLowerCase().includes('imatinib') ? 'imatinib' : 'nirmatrelvir';
                          if (!img.dataset.fallback) {
                            img.dataset.fallback = '1';
                            img.src = `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/${fallbackName}/PNG?image_size=300x300`;
                          } else {
                            img.style.display = 'none';
                          }
                        }}
                      />
                      <div className="absolute top-2 right-2 text-[9px] font-sans font-bold text-slate-700 bg-white/95 backdrop-blur-sm px-2 py-0.5 rounded-full border border-slate-200 shadow-sm">
                        NIH PubChem 2D
                      </div>
                      <div className="absolute bottom-2 left-2 text-[9px] font-mono text-emerald-400 bg-slate-950/80 backdrop-blur-sm px-2 py-0.5 rounded border border-emerald-500/30">
                        {c.molecule.id}
                      </div>
                    </div>

                    <div className="flex items-center justify-between mb-3">
                      <div className={`text-xs font-sans font-bold ${RANK_COLORS[idx]}`}>{RANK_LABELS[idx]}</div>
                      <Icon className={`w-6 h-6 ${RANK_COLORS[idx]}`} />
                    </div>

                    <div className="font-display font-bold text-lg text-white mb-0.5 truncate" title={c.molecule.name}>
                      {c.molecule.name}
                    </div>
                    <div className="text-xs font-mono text-slate-400 mb-4">{c.molecule.id}</div>

                    <div className="space-y-2 font-sans text-xs">
                      <div className="flex justify-between py-1 border-b border-white/5">
                        <span className="text-slate-400">Predicted Potency ($pIC_{50}$):</span>
                        <span className={`font-bold font-mono ${RANK_COLORS[idx]}`}>
                          {c.pIC50} <span className="text-slate-400 font-sans text-[10px]">{getRatingLabel(c.pIC50)}</span>
                        </span>
                      </div>
                      <div className="flex justify-between py-1 border-b border-white/5">
                        <span className="text-slate-400">Est. Inhibition ($K_i$):</span>
                        <span className="font-bold text-white font-mono">{c.bindingAffinityKi} nM</span>
                      </div>
                      <div className="flex justify-between py-1 border-b border-white/5">
                        <span className="text-slate-400">Binding Free Energy ($\Delta G$):</span>
                        <span className="font-bold text-white font-mono">{c.dockingScore} kcal/mol</span>
                      </div>
                      <div className="flex justify-between py-1 border-b border-white/5">
                        <span className="text-slate-400">Drug-Likeness Score:</span>
                        <span className={`font-bold font-mono ${RANK_COLORS[idx]}`}>{(c.drugLikenessScore * 100).toFixed(0)}%</span>
                      </div>
                      <div className="flex justify-between py-1">
                        <span className="text-slate-400">Molecular Mass / LogP:</span>
                        <span className="text-slate-200 font-mono">{c.molecule.mw} Da / {c.molecule.logP.toFixed(2)}</span>
                      </div>
                    </div>
                  </div>

                  <div>
                    {/* Drug-likeness bar */}
                    <div className="mt-4">
                      <div className="h-2 bg-slate-800 rounded-full overflow-hidden">
                        <div
                          className={`h-full ${idx === 0 ? 'bg-emerald-400' : idx === 1 ? 'bg-sky-400' : 'bg-amber-400'} rounded-full`}
                          style={{ width: `${c.drugLikenessScore * 100}%` }}
                        />
                      </div>
                      <div className="text-[10px] font-sans text-slate-400 mt-1 flex justify-between">
                        <span>Drug-Likeness Score</span>
                        <span>{(c.drugLikenessScore * 100).toFixed(0)}%</span>
                      </div>
                    </div>

                    {/* SMILES */}
                    <div className="mt-3 bg-surface-base/90 rounded-xl p-3 text-[10px] font-mono text-slate-300 break-all leading-relaxed max-h-16 overflow-hidden border border-white/10 shadow-inner">
                      <span className="text-white font-bold font-sans">Chemical SMILES: </span>{c.molecule.smiles}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          {/* pIC50 Chart */}
          <div className="bg-surface-container/80 backdrop-blur-md border border-white/10 rounded-3xl shadow-xl overflow-hidden">
            <button
              onClick={() => setShowChart(p => !p)}
              className="w-full flex items-center justify-between p-5 text-sm font-display font-bold text-white hover:bg-white/5 transition-colors"
            >
              <div className="flex items-center gap-2">
                <BarChart2 className="w-4 h-4 text-sky-400" />
                📊 Potency Score Distribution Chart ({predictions.length} Screened Molecules)
              </div>
              {showChart ? <ChevronUp className="w-4 h-4 text-slate-400" /> : <ChevronDown className="w-4 h-4 text-slate-400" />}
            </button>
            {showChart && (
              <div className="px-5 pb-5">
                <svg width="100%" height="130" viewBox={`0 0 ${Math.max(600, predictions.slice(0, 50).length * 12)} 130`} preserveAspectRatio="xMidYMid meet" className="w-full overflow-visible">
                  {predictions.slice(0, 50).map((pred, idx) => {
                    const barH = Math.max(8, ((pred.pIC50 - minPIC50) / range) * 90);
                    const x = idx * 12 + 2;
                    const y = 105 - barH;
                    const isTop3 = pred.rank <= 3;
                    const color = isTop3 ? '#34D399' : idx % 2 === 0 ? '#38BDF860' : '#38BDF830';
                    return (
                      <g key={pred.molecule.id} className="transition-all hover:opacity-80">
                        <rect x={x} y={y} width={9} height={barH} fill={color} rx={2}>
                          <title>{pred.molecule.name} — pIC50: {pred.pIC50}</title>
                        </rect>
                        {isTop3 && (
                          <text x={x + 4.5} y={y - 4} textAnchor="middle" fontSize="9" fill="#34D399" fontWeight="bold">#{pred.rank}</text>
                        )}
                      </g>
                    );
                  })}
                  <line x1="0" y1="105" x2="100%" y2="105" stroke="#334155" strokeWidth="1" />
                </svg>
                <div className="flex flex-wrap justify-between text-xs font-sans text-slate-400 mt-2 gap-2">
                  <span className="text-emerald-400 font-bold">🥇 #1 Lead ({mod5Data.topCandidates[0]?.pIC50})</span>
                  <span className="text-sky-400 font-bold">🥈 #2 Lead ({mod5Data.topCandidates[1]?.pIC50})</span>
                  <span className="text-amber-400 font-bold">🥉 #3 Lead ({mod5Data.topCandidates[2]?.pIC50})</span>
                  <span className="text-slate-300">Potency Range: {minPIC50.toFixed(2)} – {maxPIC50.toFixed(2)}</span>
                  <span>Rank #50 Weakest Candidate: {minPIC50.toFixed(2)}</span>
                </div>
              </div>
            )}
          </div>

          {/* Full Table */}
          <div className="bg-surface-container/80 backdrop-blur-md border border-white/10 rounded-3xl shadow-xl overflow-hidden">
            <button
              onClick={() => setShowFullTable(p => !p)}
              className="w-full flex items-center justify-between p-5 text-sm font-display font-bold text-white hover:bg-white/5 transition-colors"
            >
              <span>Full QSAR Efficacy Predictions Table ({predictions.length} Candidates)</span>
              {showFullTable ? <ChevronUp className="w-4 h-4 text-slate-400" /> : <ChevronDown className="w-4 h-4 text-slate-400" />}
            </button>
            {showFullTable && (
              <div className="overflow-x-auto border-t border-white/10 max-h-80">
                <table className="w-full text-xs font-sans text-left">
                  <thead className="bg-surface-base/90 text-slate-400 text-xs sticky top-0 border-b border-white/10 z-10 font-bold">
                    <tr>
                      <th className="p-3">Rank</th>
                      <th className="p-3">Compound Name</th>
                      <th className="p-3 font-mono">SMILES</th>
                      <th className="p-3">pIC50</th>
                      <th className="p-3">Ki (nM)</th>
                      <th className="p-3">ΔG (kcal/mol)</th>
                      <th className="p-3">Drug-Likeness</th>
                      <th className="p-3">MW</th>
                      <th className="p-3">LogP</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-white/5 font-mono text-xs">
                    {predictions.map(p => (
                      <tr key={p.molecule.id} className={`hover:bg-white/5 transition-colors ${p.rank <= 3 ? 'bg-emerald-500/10' : ''}`}>
                        <td className={`p-3 font-bold ${p.rank <= 3 ? 'text-emerald-400' : 'text-slate-400'}`}>#{p.rank}</td>
                        <td className="p-3 text-white font-sans max-w-[160px] truncate font-medium" title={p.molecule.name}>{p.molecule.name}</td>
                        <td className="p-3 text-slate-400 max-w-[120px] truncate text-[10px]" title={p.molecule.smiles}>{p.molecule.smiles}</td>
                        <td className={`p-3 font-bold ${p.pIC50 >= 8 ? 'text-emerald-400' : p.pIC50 >= 7 ? 'text-sky-400' : 'text-slate-400'}`}>{p.pIC50}</td>
                        <td className="p-3 text-emerald-400">{p.bindingAffinityKi}</td>
                        <td className="p-3 text-slate-300">{p.dockingScore}</td>
                        <td className="p-3 text-slate-300">{(p.drugLikenessScore * 100).toFixed(0)}%</td>
                        <td className="p-3 text-slate-300">{p.molecule.mw}</td>
                        <td className="p-3 text-slate-300">{p.molecule.logP}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          {/* Export Actions */}
          <div className="flex flex-wrap gap-4 pt-2">
            <button
              onClick={exportJson}
              className="flex items-center gap-2 bg-emerald-500/20 hover:bg-emerald-500/30 border border-emerald-500/50 text-emerald-300 font-sans font-bold text-xs py-3.5 px-6 rounded-2xl transition-all hover:scale-[1.01] active:scale-[0.98] cursor-pointer shadow-lg shadow-emerald-500/10"
            >
              <Download className="w-4 h-4" />
              Export Full Report (JSON)
            </button>
            <button
              onClick={exportReport}
              className="flex items-center gap-2 bg-white/5 hover:bg-white/10 border border-white/10 text-white font-sans font-bold text-xs py-3.5 px-6 rounded-2xl transition-all hover:scale-[1.01] active:scale-[0.98] cursor-pointer shadow-lg"
            >
              <FileText className="w-4 h-4 text-sky-400" />
              Download Summary Report (TXT)
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
