# -*- coding: utf-8 -*-
"""philipz89_Q#7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dY9h2-LHrQGoYcc2mHYxSj03vOCN20k2
"""

!pip install biopython

from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
import re


def find_binding_regions(sequence, tf_name, tf_pattern):
    binding_regions = []

    for match in re.finditer(tf_pattern, sequence):
        print(tf_pattern)
        print(sequence)
        start = match.start()
        end = match.end()
        binding_regions.append((start, end))
        print(f"Binding region found for {tf_name}: {start+1}-{end}")
    return binding_regions



def calculate_statistics(sequence):
    num_bases = len(sequence)
    num_cg = sequence.count('C') + sequence.count('G')
    cg_percentage = (num_cg / num_bases) * 100
    return num_bases, cg_percentage




def write_complementary_sequence(sequence, output_file):
    # Convert the sequence string to a Bio.Seq object
    bio_seq = Seq(sequence)

    # Get the complementary sequence
    complementary_seq = bio_seq.complement()

    # Write the complementary sequence to the output file
    with open(output_file, "w") as f:
        f.write(str(complementary_seq) + "\n")


def write_post_transcribed_sequence(sequence, output_file):
    # Convert the sequence string to a Bio.Seq object
    bio_seq = Seq(sequence)

    # Transcribe the sequence to RNA
    rna_seq = bio_seq.transcribe()

    # Write the transcribed RNA sequence to the output file
    with open(output_file, "w") as f:
        f.write(str(rna_seq) + "\n")


def main():
    # Load sequence from FASTA file
    input_file="seq.fasta"
    sequence_record = SeqIO.read(input_file, "fasta")
    sequence = str(sequence_record.seq)
    print(sequence)
    print(type(sequence))


    # TF binding regions
    tf_bindings = {
        "RUNX1": (r"[CGT][ACT]TGTGGT[CT][AT]", "RUNX1"),
        "TGIF1": (r"[AT]GACAG[CGT]", "TGIF1"),
        "IKZF1": (r"[CGT]TGGGA[AG][AGT]", "IKZF1"),
        #"TF2": ("TF2_pattern", "TF2_name"),
    }
    binding_regions_file = "binding_regions.txt"
    with open(binding_regions_file, "w") as f:
        for tf_name, (tf_pattern, _) in tf_bindings.items():
            print(tf_pattern)
            binding_regions = find_binding_regions(sequence, tf_name, tf_pattern)
            f.write(f"Binding regions for {tf_name}:\n")
            for start, end in binding_regions:
                f.write(f"{start+1}-{end}\n")

    # Sequence statistics
    num_bases, cg_percentage = calculate_statistics(sequence)
    stats_file = "sequence_statistics.txt"
    with open(stats_file, "w") as f:
        f.write(f"Number of bases: {num_bases}\n")
        f.write(f"Percentage of CG: {cg_percentage:.2f}%\n")

    # Complementary sequence
    complementary_file = "complementary_sequence.fasta"
    write_complementary_sequence(sequence, complementary_file)

    # Post-transcribed sequence
    post_transcribed_file = "post_transcribed_sequence.fasta"
    write_post_transcribed_sequence(sequence, post_transcribed_file)

if __name__ == "__main__":
    main()